set_look:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: room_routines
          domain: sensor
    period:
      required: false
      selector:
        text:
    track:
      required: false
      default: normal
      selector:
        select:
          options:
            - normal
            - dim
    look:
      required: false
      default: current
      selector:
        select:
          options:
            - current
            - scene
            - nothing
            - borrow
    scene:
      required: false
      selector:
        entity:
          domain: scene
switch_on:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: room_routines
          domain: sensor
          multiple: true
switch_off:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: room_routines
          domain: sensor
          multiple: true
